### ISSUE TITLE
Entrega Projeto Angular Embarque Digital

### ISSUE THREAD

**Issue by emvalencaf** [leosasantos/porto-digital-agenda#3]
### Descrição do Projeto

Uma lista de contatos _(fullstack)_ que permite a criação de novos usuários, rotas autenticadas e inclusão de contatos atrelados a usuários.

Os planos para o futuro do projeto é torná-lo uma plataforma para importar/exportar contatos (com dados de redes sociais) e automatização de mensagens _cross social media_.

O projeto se sustentaria por meio de um sistema de tier de usuários: free, premium e business; que ofereceria diferentes opções funcionalidades para a automação de mensagens para um ou mais contatos.

### Stacks
- JavaScript (TypeScript)
- Angular.js
- Node.js (Nest.js)
- MySQL

### Integrantes:
- Dayanna Vitória Piccheto
- Edson Valença Filho
- Guilherme Pinheiro
- João Henrique Barbosa
- Jonathan Wavrik
- Luís Gabriel Amorim

### Repo backend
https://github.com/emvalencaf/nestjs-backend-contactsbook

### Repo frontend
https://github.com/emvalencaf/nestjs-frontend-contactsbook

### Anexos:
Zip do projeto (com o arquivo docker-compose.yaml para buildar o projeto).
[projeto.zip](https://github.com/user-attachments/files/15794760/projeto.zip)

Zip do projeto só com o **frontend** funcionando com a memória da aplicação (**conforme solicitado**)
 [frontend-cache.zip](https://github.com/user-attachments/files/15808281/frontend-cache.zip)
  - consta 3 rotas: lista de contatos, atualização de contato específico e criação de outro contato.
 - CRUD: criação de um novo contato, edição do perfil do contato, atualização de um contato existente e deleção do contato. (tudo na memória da aplicação).
 
 ### Como usar o só o Front-end
 - Baixe o arquivo `zip` só com o front-end destacado nessa issue;
 - Abra o terminal na pasta do projeto e executar o comando `ng serve`.

### Como Usar o Full-Stack

1. Abrir o terminal no diretório `bd` e executar o comando para buildar a imagem do banco de dados com o comando `docker build -t mysql .`:

![print_init_db_p1](https://github.com/leosasantos/porto-digital-agenda/assets/102879625/7b9625fe-5cd3-4759-8520-66f312f3a106)

2. Ainda no terminal, execute o comando para iniciar um container com o banco de dados com o comando `docker run -p 3306:3306 mysql` e aguarde até o **banco de dados ser populado**.

![print_init_db_p2](https://github.com/leosasantos/porto-digital-agenda/assets/102879625/58a26f0f-66f4-49b3-b70d-0eccb42e6550)

3. Abra um novo terminal (mantenha o anterior aberto) no diretório `backend`  e execute o comando `npm run start:dev` e aguarde até buildar o backend:

![print_init_backend_p1](https://github.com/leosasantos/porto-digital-agenda/assets/102879625/cd5d4d87-ad15-4112-9ec1-2a790d0d1a67)
![print_init_backend_p2](https://github.com/leosasantos/porto-digital-agenda/assets/102879625/488b5a1e-4572-4c38-93a7-3cec02c66b28)

4. Abra um terceiro terminal (não feche os outros dois) no diretório `frontend` execute o comando `ng serve`:

![print_init_frontend_p1](https://github.com/leosasantos/porto-digital-agenda/assets/102879625/3baf4bd8-11fc-478e-9e97-4d48ddf32005)

***Observação**: em caso de usar o docker-compose e o backend quebrar, reiniciá-lo isso ocorre porque, às vezes, o backend inicia antes do banco de dados. Então, uma vez que o container for buildado pode reiniciar o backend.

### Telefone contato
(81) 9.99633-9891

**Comment by ferfox1981** [comment]
Não estamos conseguindo levantar o backend (algo desnecessário para o projeto).
Solicitamos retirar  o backend simplificando por um array ou JSON-SERVER.
O backend é desnecessário, apenas um fator que pode complicar a correção devido ao setup.

**Comment by ferfox1981** [comment]
Conseguimos rodar (y)
