### ISSUE TITLE
Entrega Projeto Angular Embarque Digital - Vilton

### ISSUE THREAD

**Issue by Viltonedson** [leosasantos/porto-digital-agenda#4]
_### **Descrição do Projeto**_
Esse projeto é de uma agenda telefone de contatos

**Grupo:**
Vilton Edson Figueirôa de Moura

**Stacks**
- JavaScript (TypeScript)
- Angular.js
- Node.js (Nest.js)

**Anexos:** 
[agenda-telefonica-angular.zip](https://github.com/user-attachments/files/15827371/agenda-telefonica-angular.zip)
(ATUALIZADA 2.0)

**Contato:**
(81) 98688-3141

**Comment by ferfox1981** [comment]
Nao estamos conseguindo levantar o frontend, qual a versão do node e do Angular usados?
![image](https://github.com/leosasantos/porto-digital-agenda/assets/53412477/e5d7972d-110e-478e-b675-1a457d2890e8)
