### ISSUE TITLE
Entrega Projeto Angular Embarque Digital - Denilson Delgado e Hugo Leonardo

### ISSUE THREAD

**Issue by ddelgadopy** [leosasantos/porto-digital-agenda#7]
[Uploading agenda-serpro  Denilson e Hugo.zip…]()

**Comment by Emmanueel2003** [comment]
Eles esqueceram de por, mas eu também estou no grupo 
Emanuel Marcos do nascimento

**Comment by ferfox1981** [comment]
A equipe seria esta?
DENILSON DELGADO CORREIA
HUGO LEONARDO DA SILVA SANTANA
EMANUEL MARCOS DO NASCIMENTO

**Comment by ferfox1981** [comment]
O Zip do projeto não está baixando

**Comment by Emmanueel2003** [comment]
Sim seria essa a equipe sim
