### ISSUE TITLE
Entrega do Projeto Final - Angular

### ISSUE THREAD

**Issue by iagovieir** [leosasantos/porto-digital-agenda#9]
Stacks
- JavaScript (TypeScript)
- Angular.js
- Json Server

Integrantes:

- Afonso luna
- Iago Vieira
- Luiz Paulo Machado
- Mateus Moraes
- Rômullo Moura

Repo do projeto
https://github.com/iagovieir/agenda-front

Contato: 81 99529-2810 ou iago.unijp@gmail.com

**Comment by ferfox1981** [comment]
Obrigado Iago
